### ISSUE TITLE
Analogue inputs

### ISSUE THREAD

**Issue by AndyS64** [shortbloke/node-red-contrib-automation-hat#1]
Hi ShortBloke

Thanks for taking the time and effort to develop and publish your AutomationHat Node-Red code

I notice your conversation with Pimoroni about the python library and was wondering how you got on with resolving the analogue input issues ?

I'd offer to help, but unfortunately I'm not much of a programmer and when I look at code like yours and assume its been written by the gods :-)

Cheers

Andy

**Comment by shortbloke** [comment]
Hi Andy, After contacting Pimoroni I set about trying to get the inputs working without any luck. I'm sure it can be done, I've just not had the time or personal need to add this support since my immediate requirement when using this hat was for the output stage. My development Pi with the AutomationHAT still fitted is sitting on my desk in front of me, so I make get round to attempting to get it working again, though I can't promise when, sorry.

**Comment by AndyS64** [comment]
Hi Martin

Thanks for the update. I’m just replacing a garden irrigation system so really just need 3 relays. Then I thought I could monitor temperature and then what else

Anyway I’ve got the basics up and running and at least the irrigation system can be controlled from anywhere in the world ☺

I noticed that you submitted a question to Ronnyvdbr. I’ve also looked at his git repo. He appears to be using the ExplorerHat straight from Pimoroni, so I assumed that they are basically the same beasts under the hood. Tried it and got a pretty gauge working. But the readings were jumping about. Popped off to Pimoroni git repo and saw that others are having the same problem with the ExplorerHat and random analogue readings. So not a AutomationHat issue. And Gadgetoid @ Pimoroni has flagged it as a bug and is asking for help ☹

Looks like Node-Red, AutomationHat and analogue inputs are going to be one of those issues that never gets fixed. Shame, they make a nice package

I’d be interested to hear how you get on if you manage to get back to

Cheers

Andy


Andrew Speedie | Technical Director | Secure IT Disposals Ltd
Tel: 0870 727 1578 | Email: andy@sitd.co.uk<mailto:andy@sitd.co.uk> | Skype: andy@sitd.co.uk<callto:andy@sitd.co.uk> | Web: www.sitd.co.uk<https://www.sitd.co.uk/>

**Comment by shortbloke** [comment]
Andy, Feel free to subscribe to this repo, so that if/when I get back to making some changes you should get a notification. For now I'll close this issue ticket, since the lack of input support is already on my documented todo list. 
Martin

**Comment by shortbloke** [comment]
@AndyS64 I've implemented support for analog and digital/buffered inputs in an initial release. If you are still interested I'd welcome you giving it a try and seeing if it works for you or not.
#3473a05

**Comment by shortbloke** [comment]
No Feedback. Closing as resolved.
